### ISSUE TITLE
Allow net-ldap v0.7.0 

### ISSUE THREAD

**Issue by onceking** [cschiewek/devise_ldap_authenticatable#173]
it contains a fix for authenticating against Microsoft Active Directory with StartTLS

details:
https://github.com/ruby-ldap/ruby-net-ldap/pull/95

**Comment by MarkoHiel** [comment]
Is there someone working on this, because all Versions < 0.6.0 have the following vulnerability:

> Net::LDAP for Ruby lib/net/ldap/password.rb SSHA Password Generation Weak Salt
> CVE 2014-0083
> Patched Versions >= 0.6.0

**Comment by lukad** [comment]
:+1:
