### ISSUE TITLE
Devise::Authenticatable is misspelled thus breaking gem

### ISSUE THREAD

**Issue by acurley** [cschiewek/devise_ldap_authenticatable#195]
Current spelling is Autheneticatable, which produces a NameError on startup.  This typo breaks the gem.

**Comment by gustaflindqvist** [comment]
Good working on finding the misspelled class name @acurley! I hope it gets merge ASAP.

**Comment by acurley** [comment]
@gustaflindqvist, unfortunately I was the person who caused the misspelling in my last PR! :(

**Comment by gustaflindqvist** [comment]
@acurley I think it's time for devise_ldap_authenticatable to not working against master to get the latest version of the gem. Time to update the version tag and create releases, maybe?

**Comment by acurley** [comment]
@cschiewek, what do you think?  Sent to rubygems a new release so we can stop working against master to get the most up to date code?

**Comment by cschiewek** [comment]
Just merged.  Pushing to rubygems shortly.

**Comment by gustaflindqvist** [comment]
@cschiewek Awesomeness!

**Comment by cschiewek** [comment]
v0.8.3 is now live on rubygems

**Comment by gustaflindqvist** [comment]
@cschiewek then I finally can add:

```ruby
gem 'devise_ldap_authenticatable', '0.8.3'
```

Better for the production server. :+1:

**Comment by acurley** [comment]
@cschiewek Thanks so much!  :+1:

**Comment by cschiewek** [comment]
You're welcome! :)

**Comment by drobny** [comment]
@cschiewek Thanks for pulling this in. I also noticed that the previous merge assumed that find_for_ldap_authentication always returns a resource object but it could be nil if auth keys are left blank. I made a pull request #193 that sorts this as well. Might not be relevant so sorry if I am butting in!

**Comment by cschiewek** [comment]
I pulled it in as well.  So your change is in master and will be in the next gem release.  

If any of you are using this on a regular basis and would like to help contribute, let me know and I'll give you rights on the repo.  We've moved away from LDAP to SAML, so I'm not using much anymore and would love help from folks who are using it day to day.

**Comment by acurley** [comment]
@cschiewek I and my team use this gem in all of our applications.  I would love to help out with the maintenance burden.

**Comment by cschiewek** [comment]
@acurley I've just added you as a contributor.  Do you have a rubygems account?  If so, let me know what it is and I'll give you publishing rights there as well.

**Comment by gustaflindqvist** [comment]
Me too! 



—

**Comment by cschiewek** [comment]
Done!  If you guys have the time, it would be great if we could clear up the backlog somewhat.  I'm willing to guess a bunch of those issues are non-starters and just need to be closed.

**Comment by acurley** [comment]
Agreed.  I will start taking a look this evening (US Eastern)
