### ISSUE TITLE
Incorrect Devise requirements in Gemspec

### ISSUE THREAD

**Issue by LewisCarey2** [cschiewek/devise_ldap_authenticatable#199]
https://github.com/cschiewek/devise_ldap_authenticatable/commit/b0b676f26973d33a074236f0570505bdb2eef229 introduces a dependency on the `remember_me` method in devise

This method was introduced in devise 3.4.1 here https://github.com/plataformatec/devise/commit/7029a5aaa88fcee9a9bf25a63d0105ad97728d08

Therefore your gem now requires `devise >= 3.4.1` if used together with `remember_me` functionality on a form.  That's a little bit awkward I know, since the dependency really depends how the user combined functionality outside of your gem.

**Comment by ryoqun** [comment]
I'm affected this issue too...

@cschiewek Could you take a look at this?

@LewisCarey2 you're not alone.. ;)

**Comment by cschiewek** [comment]
Updated gem with this change has been pushed to rubygems.

**Comment by ryoqun** [comment]
@cschiewek thank you very much!
