### ISSUE TITLE
Net::LDAP Search works but login fails 

### ISSUE THREAD

**Issue by imkarthikk** [cschiewek/devise_ldap_authenticatable#203]
I've been stuck at this for about 15 hours. It's on the verge of throwing my laptop. The weird issue is, the LDAP search/listing works PERFECTLY. It binds with the username and password I've given and shows all the users who have that attribute (eg, CN, UID, sAMAaccountName). However when I try to login, it shows:

![screen shot 2015-05-01 at 4 00 47 pm](https://cloud.githubusercontent.com/assets/973265/7429234/c8a545f0-f01b-11e4-9a62-b98526655700.png)

This is how I listed all the users,

![screen shot 2015-05-01 at 4 01 08 pm](https://cloud.githubusercontent.com/assets/973265/7429235/d446a2e6-f01b-11e4-83ef-e1e3ecb5b3e4.png)

ANY help would be immensely appreciated!

**Comment by acurley** [comment]
Have you changed the default authentication key in `config/initializers/devise.rb`?  It should look like this:

```
Devise.setup do |config|
....
config.authentication_keys = [:username]
....
end
```

In your screen shots it looks like you are using a username but the default for this gem is `:email`.
