### ISSUE TITLE
Security vulnerability with net_ldap < 0.60

### ISSUE THREAD

**Issue by tobioboye** [cschiewek/devise_ldap_authenticatable#205]
The vulnerability scanner database has a vulnerability entry for `net_ldap < 0.60`, the salt value used for passwords seems to be too weak [1].

There's a patch available with `net_ldap >= 0.60` but `devise_ldap_authenticatable` seems to currently support `net_ldap < 0.60`. Are there any plans to upgrade the net_ldap version?

[1] https://github.com/rubysec/ruby-advisory-db/blob/master/gems/net-ldap/OSVDB-106108.yml

Thanks,
Tobi

**Comment by skaasten** [comment]
See #206

**Comment by cschiewek** [comment]
Dupe and resolved.
