### ISSUE TITLE
adjustment to the wiki?

### ISSUE THREAD

**Issue by tuvya** [cschiewek/devise_ldap_authenticatable#225]
Hi everyone,

thank you for this gem. 

I just installed:
- rails 5.0.0.rc1
- devise_ldap_authenticatable 0.8.5
- devise 4.1.1

using it with Windows Active Directory. Following the instructions in the wiki, it was no problem and works like a charm. 

Two minor modifications were necessary in the models/user.rb. _get_ldap_id_ returned nil. I just commented it out. I had to rename the so called "# hack for remember_token" to _def authenticatable__**salt** (in the wiki: authenticatable_token)

Hope this may help.

**Comment by cseelus** [comment]
@tuvya Afaik you can make the adjustments to the wiki yourself

**Comment by androidand** [comment]
I can confirm that the hack needs to be renamed to "authenticatable_salt", at least when using rails 5.

**Comment by olleolleolle** [comment]
@tuvya Thanks for adding this, I changed the wiki page to include this.

https://github.com/cschiewek/devise_ldap_authenticatable/wiki

Can this now be closed?
