### ISSUE TITLE
rails-5 + devise-4.2.1

### ISSUE THREAD

**Issue by akam-it** [cschiewek/devise_ldap_authenticatable#237]
Hello!
is this gem support rails-5 + devise-4.2.1?

I've got errors
NameError in Devise::SessionsController#create
undefined local variable or method `scoped' for #<Class:0x000000036a1a78> Did you mean? scope unscoped

**Comment by njt1982** [comment]
self closed? What was the result?

**Comment by masciugo** [comment]
@njt1982 did you try with rails5. It works? tnx
