### ISSUE TITLE
Devise::LdapAdapter.get_ldap_param not retrieving attributes

### ISSUE THREAD

**Issue by link82** [cschiewek/devise_ldap_authenticatable#94]
Hello, I'm trying to use ldap_authenticatable to authenticate domain users in my application.
Ldap lookup seems to work correcly, i get authenticated but i receive no attribute for my user and if I try to get them using "get_ldap_param" on before_save it returns nil.

I tried to connect simply using Ldap gem and i receive correctly every attribute.

Here my config:

  # ==> LDAP Configuration 
  config.ldap_logger = true
  config.ldap_create_user = true
  config.ldap_update_password = true

This is the console output:

  LDAP: LDAP dn lookup: cn=davide
  LDAP: LDAP search for login: cn=davide
  LDAP: Authorizing user cn=davide,ou=Users,ou=NET1,dc=company,dc=local
  LDAP: LDAP dn lookup: cn=davide
  LDAP: LDAP search for login: cn=davide

**Comment by spcurry** [comment]
I've also run into this problem, and wasted a bunch of time debugging then writing my own workaround. Definitely not the same as issue #69.

**Comment by rnickmccandless** [comment]
Confirmed that this is still an issue in version [`v0.8.5`](https://github.com/cschiewek/devise_ldap_authenticatable/releases/tag/v0.8.5). 

With the help of @jpatokal pull request code, I was able to work around the issue by creating a private function within the `User` model:

```ruby
class User < ApplicationRecord
  [...]

  def ldap_before_save
    self.email = get_ldap_param('mail')&.first
    self.name  = get_ldap_param('displayName')&.first
  end

  private

  def get_ldap_param(attribute)
    options = {
      login:                      login,
      password:                   password,
      ldap_auth_username_builder: ::Devise.ldap_auth_username_builder,
      admin:                      ::Devise.ldap_use_admin_to_bind
    }

    resource = Devise::LDAP::Connection.new(options)
    resource.authenticate! if password
    resource.ldap_param_value(attribute)
  end
  [...]
end
```

**Comment by HaziFlorinMarian** [comment]
> 

Hi!
Can you share values for local variables login/password?
Thank you!
